name: Gkui Test and Coverage

on: [push, pull_request]

jobs:
  build:
    name: Test and Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Run Confluent Platform (Confluent Server and Confluent Schema Registry)
      uses: ybyzek/cp-all-in-one-action@v0.2
      with:
        service: schema-registry

    - name: Run Confluent Platform (Confluent Server and Confluent Schema Registry)
      uses: ybyzek/cp-all-in-one-action@v0.2
      with:
        service: zookeeper

    - name: Run Confluent Platform (Confluent Server and Confluent Schema Registry)
      uses: ybyzek/cp-all-in-one-action@v0.2
      with:
        service: broker


    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Run Tests
      run: go get ./... && go test -v ./...

    - name: Show Test Coverage
      run: go test -cover ./...

  e2e:
    name: Test End to End
    runs-on: ubuntu-latest


#To connect to services in Docker, refer to the following ports:
#
#ZooKeeper: 2181
#Kafka broker: 9092
#Kafka broker JMX: 9101
#Confluent Schema Registry: 8081
#Kafka Connect: 8083
#Confluent Control Center: 9021
#ksqlDB: 8088
#Confluent REST Proxy: 8082

#    services:
#      # Label used to access the service container
#      zookeeper:
#        # Docker Hub image
#        image: confluentinc/cp-zookeeper:latest
#        env:
#          ZOOKEEPER_CLIENT_PORT: 2181
#          ZOOKEEPER_TICK_TIME: 2000
#        options: >-
#          --health-cmd "echo mntr | nc -w 2 -q 2 localhost 2181"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 22181:2181
#      kafka:
#        image: confluentinc/cp-kafka:latest
#        ports:
#          - 29092:29092
#        options: >-
#          --health-cmd "kafka-broker-api-versions.sh --version"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        env:
#          KAFKA_BROKER_ID: 1
#          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1